---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Название
  description: 'Введите название продукта '
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: 'Описание '
  description: 'Введите описание продукта '
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: caterories
      file: 
      path: 
  label: 'Категория '
  description: 'Выберите категорию продукта '
- name: product_image
  type: file
  config:
    maxSize: '20'
  label: Product image
  description: Hero (main) image of the priduct
  default: "/uploads/logo3.png"
- name: product_price
  type: number
  label: Product price
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
  description: Price for this product
- name: product_old_price
  type: number
  description: Previous price of the product before discount
  default: '0'
  required: true
  config:
    min: 
    max: 
    step: 
  label: Product old price
- name: product_image_gallery
  type: image_gallery
  config: {}
  label: Product image gallery
  description: Further images for the product
- name: product_size
  type: select
  default: ''
  config:
    required: false
    options:
    - XS
    - " S"
    - M
    - L
    - XL
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Product size
  description: Size for the product
pages:
- products/t-shirt.md
- products/Kids/kids-dress.md
