---
label: Product
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: true
  label: Название
  description: 'Введите название продукта '
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: 'Описание '
  description: 'Введите описание продукта '
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: caterories
      file: 
      path: 
  label: 'Категория '
  description: 'Выберите категорию продукта '
- name: image
  type: file
  config:
    maxSize: '20'
  default: https://res.cloudinary.com/da4me/fl_progressive/v1565021018/uploads/logo2_lawxwe.png
  label: 'Основная картинка '
  description: Выберите основную картинку
- name: price
  type: number
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
  label: Цена
  description: Введите актуальную цену
- name: old_price
  type: number
  default: '0'
  required: true
  config:
    min: 
    max: 
    step: 
  label: 'Старая цена (если есть) '
  description: Введите старую цену до скидки
- name: image_gallery
  type: image_gallery
  config: {}
  label: Галерея
  description: Выберите дополнительные картинки для слайдера
- name: size
  type: select
  default: ''
  config:
    required: false
    options:
    - XS
    - " S"
    - M
    - L
    - XL
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Размер
  description: Выберите размер, если есть
- name: colors
  type: field_group
  config: {}
  fields:
  - name: color1
    type: color
    config:
      required: false
      color_format: Hex
    label: Цвет1
    description: Выбрать альтернативный цвет
  - name: images_color1
    type: image_gallery
    config: {}
    label: Картинки для изделий с цветом 1
    description: 'Выбрать картинки для продукта с другим цветом '
  label: Другие цвета
  description: 'Выберите цвет и картинки '
