---
label: Product
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: true
  label: Название
  description: 'Введите название продукта '
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: 'Описание '
  description: 'Введите описание продукта '
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: caterories
      file: 
      path: 
  label: 'Категория '
  description: 'Выберите категорию продукта '
- name: image
  type: file
  config:
    maxSize: '20'
  default: https://res.cloudinary.com/da4me/fl_progressive/v1565021018/uploads/logo2_lawxwe.png
  label: 'Основная картинка '
  description: Выберите основную картинку
- name: price
  type: number
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
  label: Цена
  description: Введите актуальную цену
- name: old_price
  type: number
  default: '0'
  required: true
  config:
    min: 
    max: 
    step: 
  label: 'Старая цена (если есть) '
  description: Введите старую цену до скидки
- name: image_gallery
  type: image_gallery
  config: {}
  label: Галерея
  description: Выберите дополнительные картинки для слайдера
- name: colors
  type: field_group
  config: {}
  fields:
  - name: color1
    type: color
    config:
      required: false
      color_format: Hex
    label: Цвет1
    description: Выбрать альтернативный цвет
  - name: images_color1
    type: image_gallery
    config: {}
    label: Картинки для изделий с цветом 1
    description: 'Выбрать картинки для продукта с другим цветом '
  - name: color2
    type: color
    config:
      required: false
      color_format: Hex
    label: Цвет 2
    description: Выберите цвет № 2
  - name: images_color2
    type: image_gallery
    config: {}
    label: Картинки для изделия с цветом 2
    description: Выберите картинки для изделия с цветом №2
  - name: color3
    type: color
    label: Цвет3
    config:
      required: false
      color_format: Hex
    description: Выбрать альтернативный цвет
  - name: images_color3
    type: image_gallery
    config: {}
    label: Картинки для изделия с цветом 3
    description: Выберите картинки для изделия с цветом №3
  label: Другие цвета
  description: 'Выберите цвет и картинки '
- name: article
  type: text
  config:
    required: true
  label: Артикул товара
  description: 'Введите артикул товара для учета  '
- name: size
  type: tag_list
  default:
  - XS
  - S
  - M
  - L
  - XL
  label: Размер
  description: Добавьте возможные размеры для продукта через запятую(S, M и т.д.).
    Если доступны все размеры оставьте поле пустым
pages:
- products/Платья/платье-летнее.md
- products/Kids/комбинезон.md
- products/Family look/сарафаны-для-мамы-и-малышки.md
- products/Kids/футболка.md
- products/Платья/платье-в-пол.md
- products/Юбки/юбка-летняя.md
- products/Юбки/юбка-в-пол.md
- products/Сарафаны/сарафан-бомба.md
- products/Сарафаны/сарафан-бархат.md
