---
label: 'Theme config '
hide_body: true
fields:
- type: text
  name: site_name
  label: Имя сайта
  description: Введите название сайта
- type: textarea
  name: site_description
  label: Описание сайта
  description: Введите описание сайта
- type: textarea
  name: hero_title
  config:
    wysiwyg: true
    schema:
      format: html
  label: Заголовок главной страницы
  description: Введите заголовок для главной страницы
- type: textarea
  name: hero_subtitle
  config:
    wysiwyg: true
    schema:
      format: html
  label: Подзаголовок главной страницы
  description: 'Введите Подзаголовок для главной страницы '
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- name: footer_bg
  type: file
  config:
    maxSize: 250
  label: Фон для футера
  description: Картинка для футера
pages:
- data/theme.json
